# yaml 格式注意
# 以"空格為主"，不能使用跳格字元(TAB)
# 數量自訂，此用 4 space

version: 1
disable_existing_loggers: True #是否覆蓋以前的配置logger
formatters:
        default:
            #format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            format: "%(asctime)s   %(levelname)s:   %(message)s"
        wrong_command:
            format: "---- WARN ---- %(asctime)s   %(levelname)s:   %(message)s ---- WARN ----"

root: #默認情況下配置
    level: INFO #DEBUG資訊不會顯示
    handlers: [console,info_file_handler,warning_file_handler]
 
loggers: #如果有設定loggers的話會採用，否則採用root設定
    my_module1: 
            level: INFO
            handlers: [console,info_file_handler,warning_file_handler]
            propagate: no
    my_module2: #沒有console
            level: INFO
            handlers: [info_file_handler,warning_file_handler]
            propagate: no
    my_module3:
            level: WARN
            handlers: [console,info_file_handler,warning_file_handler]
            propagate: no
    my_module4: #沒有console
            level: WARN
            handlers: [info_file_handler,warning_file_handler]
            propagate: no
 
handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: default
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: default
            filename: ./logs/log.txt
            maxBytes: 5242880
            backupCount: 1
            encoding: utf8
    warning_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: WARN
            formatter: wrong_command
            filename: ./logs/log.txt
            maxBytes: 5242880
            backupCount: 1
            encoding: utf8